---
# original defaults
inotify_instances: 128
inotify_watches: 8192

arch_host: nsaserver.pat.sdm.noao.edu
arch_port: 9000
arch_timeout: 11
arch_irods_host: db.pat.sdm.noao.edu
arch_irods_port: 1247
arch_irods_resource: tadaResc
archive_irods331: /noao-tuc-z1/tada/ 
irodsdata: 'puppet:///modules/dmo-hiera/iinit.in'
irodsenv: 'puppet:///modules/dmo-hiera/irodsEnv.dev'
localdjango: 'puppet:///modules/dmo-hiera/django_settings_local_pat.py'
nginx_conf: 'puppet:///modules/dmo-hiera/nginx.conf'
smoke_conf: 'puppet:///modules/dmo-hiera/smoke-config.dev.sh'
mars_vhost: www.mars.noao.edu

#mars_host: mars.vagrant.noao.edu
mars_host: mars1.sdm.noao.edu
mars_port: 8000

tadaversion: dev
dataqversion: dev
marsversion: dev
