---
###
### For use in vagrant dev ENV with NATICA.
### For PAT equiv with hiera5, see:
###    dmo_hiera/hieradata/pat/common.yaml
###


####################
## NATICA
##

localnatica: 'puppet:///modules/dmo_hiera/django_settings_local_dev_natica.py'
djangoserver: /sandbox/marsnat/start-mars-development.sh
elasticsearch_host: 'http://docker1.dm.noao.edu'

natica_timeout: 2 # arch_timeout: 11

natica_host: marsnat.vagrant.noao.edu
natica_port: 8000
dq_host: localhost
dq_port: 9988
#tadanatversion: master
#marsnatversion: ingest2
#hdrfunclibversion: master
#marsnatversion: refactor-urls
marsnatversion: master
dqnatversion: master
personalityversion: master

archive_topdir: '/sandbox/natica-archive'
patch_dbnat: 'puppet:///modules/dmo_hiera/patch-dbnat.sh'
patch_marsnat: 'puppet:///modules/dmo_hiera/patch-marsnat.sh'
#! patch_tadanat: 'puppet:///modules/dmo_hiera/patch-tadanat.sh'
marsnat_pubkey: 'puppet:///modules/dmo_hiera/spdev1.id_dsa.pub'
marsnat_privkey: 'puppet:///modules/dmo_hiera/spdev1.id_dsa'
test_val_host: valnat.vagrant.noao.edu
test_mtn_host: mtnnat.vagrant.noao.edu
guconf: 'puppet:///modules/dmo_hiera/gunicorn-conf.py'
